name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Switch to production branch
      run: git switch production
    - name: Install pdf converter
      run: sudo apt-get install -y poppler-utils
    - name: Convert pdf CV to png
      run: pdftoppm public/cv.pdf public/images/cv.png -png
    - name: Install Node.js
      uses: actions/setup-node@v3
    - name: Install npm dependencies
      run: npm install
    - name: Init npm
      run: npm init -y
    - name: Build website
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    outputs:
      job_status: ${{ job.status }}

  push-on-pages:

    runs-on: ubuntu-latest

    needs:
      - build
    if: "always()&&(needs.build.outputs.job_status=='success')"

    steps:
      - uses: actions/checkout@v3
      - name: Set git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Switch to gh-pages branch
        run: |
            git fetch --unshallow
            git switch gh-pages
            git rm -r *
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: .
      - name: Push on gh-pages
        run: |
            git add .
            git commit -m "Upload production application on website" --allow-empty
            git push origin gh-pages
      - name: Test
        uses: boro2g/http-request-action@v1.0.2
        with:
          url: 'https://api.github.com/repos/Curs3W4ll/corentin-hervaud/pages'
          method: 'PUT'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"}'
          data: '{"cname": "www.hervaud.fr", "source": {"branch":"gh-pages","path":"/"}}'
